### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abhimanyu003** [kilroyweb/homeboy#4]
Really great tool, thanks for creating this. There are few features like to use. I know they can done by modifying homestead.yml file. These are just suggestions.

- [ ] Show all hosts/sites
- [ ] Remove a host
- [x] Boot up homestead vm by doing `homeboy boot` or something

**Comment by cthom-dev** [comment]
+1.

**Comment by kilroyweb** [comment]
Added a new command "homeboy vagrant" which will let you drop in any vagrant command:
```
homeboy vagrant status
``` 

We should be able to implement showing existing sites by reading the sites section of homestead.yaml, I'm probably going to hold off on trying to removing the host (for now) though since that can get a bit messy depending on how things are implemented

**Comment by kilroyweb** [comment]
Also just added in the "file" command, it doesn't parse the data in any way, but should be a nice way to view the existing sites:

```
homeboy file hosts
homeboy file homestead
```
