### ISSUE TITLE
Use Defaults Option For Instant Setup

### ISSUE THREAD

**Issue by dillingham** [kilroyweb/homeboy#9]
A cool feature might be to add an argument to the homeboy command to instantly use defaults for an expedited setup.  Kind of how quick valet is to setup.

Asks questions
>php homeboy 

Skips questions and uses all defaults

> php homeboy project-name

db: `project-name`  & `project-name.app` etc

I can submit a PR if this is something you think should happen

**Comment by iforwms** [comment]
+1.

**Comment by kilroyweb** [comment]
Yeah I planned on setting up something similar by passing options to auto fill any of the questions. Will probably end up looking something like this:

homeboy --name=project-name --use-defaults=true

**Comment by kilroyweb** [comment]
All set, make sure to use the "homestead host" command or else options won't work. ie:

homeboy host --name=my-project --use-defaults --skip-confirmation

Not sure if there's a way around that, but added info in the readme

**Comment by dillingham** [comment]
I feel like "homeboy project-name" would of been cleaner. I personally would never remember those flags. The questions are already auto filled minus the name, so none of those flags are needed

**Comment by briandillingham** [comment]
The questions are already auto filled minus the name

**Comment by kilroyweb** [comment]
It's a limitation of how the Symfony console takes arguments/options afaik. It doesn't seem like options can be added on when calling the default command, which is why it needs to be called explicitly with "homeboy host".

We could make the "project name" an argument, so "homeboy host [name]" would technically work, but I think this might cause issues using other option flags, as the name arg would alway be required when using those flags.

I could be wrong though, I'd need to look more into it

**Comment by kilroyweb** [comment]
This would be a pretty easy alias to setup though, ie
homeboyhost="php homeboy host --name=$"
